language: ruby
rvm:
- 2.5.0
before_script:
- bundle exec rake db:create --all
- bundle exec rake db:migrate
script:
- bundle exec rake ci:tests
services:
- postgresql
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: Kfn7hRG/ZbBuewzGkK0zoYOn/fOqtPa4W2tyIFKctay+R4tVhvgBvlbrwar7GH3bTs4JTJaPRHLRWV3HW21E518TDzDA+Y33VLfhO4Nm/YOHBWsCxo8D0VyofiNtT1bMAEN8Jo2ROsOTT4dziTWBKVDrcTnion9bAo3Ik6fixBW06s/xyYJxUPliyy++yFxG4OBLQ6mY27sbKVnoW7QQMblbN/WDvj1Tbk37d1y1XekICZvd3xlnHgIGfQt3/LPo1v1hwgQUigy3TMOuI9nGNb3cGgMtqxLkV4K8Ggq8gQKBYtBIiWhn8GvFzTtqWGQ2iz3QuV9yOjHTJNhGvX5cqj1Lh5GxDc4c89apOAqRgI7EZ04ZSj3lPMh8DKBS/F2NEYHp6LYPP56g5tIns0Y4m17QCgwPMS/CkRN6fXe+tMi0avY3z/7QTUxNf67B70u95UF/NLX98qHorKvRkaHuoavwB+yUsMzyoogOQwWZrwp12JbEKkmK4HAaTN2CpiXk37N3P3r4PsQMQUWpplqBPZVcZZNmqnpECOCH+ihU2WQsi6xruK/l04iCuUf0FDmJYtpGC91AlzTN7G1P+Z3eass0Ry4o6pZaN/CHgCVF200Y1GJnvFmiWqj/SJ5pgqOnzqW4ep90V26eObDcehlMdrK2cOhBL5Hz79clnggTLHM=
  app:
    develop: software2projectdev
    master: software2projectprod
  on:
    repo: devpablin/Software2Project
  run:
    - "rails db:migrate"
