language: ruby
rvm:
- 2.5.0
before_script:
- bundle exec rake db:create --all
- bundle exec rake db:migrate
script:
- bundle exec rake ci:tests
services:
- postgresql
notifications:
  email: false
  slack:
    secure: QmNzHmHT6rwBBbjoKLsB57wpc//A3JTUWAXgQ5TQX9wGXW+HakaiysSA6nj7hjBb1ckmvGGGXsnts0Mar4HtCFhxnSn55r38cLgGod/zxDr6fUB3pa3lwn9sBxVKyynkJILJhMYM4POq1WeUm53eeq82oRZkqHoETx/rYxYL0K7crY/Ax1FgTHu5GYgez5mlj651YsCVVL5ULlaWgn9G0P4wNwJFzWvKbSKN5TsvyqRW/j5Ahxp01HMe9t+N1lEKgyZUrCgJGrEYk1qYhYpkwylIYVs34PcenNQebbbUwGBHXZBpiVEmqpjkR9l6FaMWfHoWqJuC/61gUbsZ+GGsBCG2AU+hWKHouEuY2PeBrOJH/QLH505bb9GCW7Qtd+y0Ydh6NAdmJlDyGe4GS1YTOY+CrhQ7LBLlFkmgGKYQifd3gjJpVekIsSrOT5UXRjFOK+B9CsDC3CItTCjpYyDRHUPNE631OWbbYToGBSaKhcMbJf659gASzEd1Kd7YLPn+dzl8elLoRRpkb1FIu46G+3x5ZgI0H9deoTPjBxqiL85uXYhgVgqMPh4Rc/NQFu0SQAJBle/i9H7pGNLJtgDHDRs2RZA3LxImEG0FxFvAtGTlWRXJlEOBQ/Al7tHh3C6AeDGdH6CqnOmK57wtDn5fhhMOpCcqUDadgGLgrQTuP30=
deploy:
  provider: heroku
  api_key:
    secure: Kfn7hRG/ZbBuewzGkK0zoYOn/fOqtPa4W2tyIFKctay+R4tVhvgBvlbrwar7GH3bTs4JTJaPRHLRWV3HW21E518TDzDA+Y33VLfhO4Nm/YOHBWsCxo8D0VyofiNtT1bMAEN8Jo2ROsOTT4dziTWBKVDrcTnion9bAo3Ik6fixBW06s/xyYJxUPliyy++yFxG4OBLQ6mY27sbKVnoW7QQMblbN/WDvj1Tbk37d1y1XekICZvd3xlnHgIGfQt3/LPo1v1hwgQUigy3TMOuI9nGNb3cGgMtqxLkV4K8Ggq8gQKBYtBIiWhn8GvFzTtqWGQ2iz3QuV9yOjHTJNhGvX5cqj1Lh5GxDc4c89apOAqRgI7EZ04ZSj3lPMh8DKBS/F2NEYHp6LYPP56g5tIns0Y4m17QCgwPMS/CkRN6fXe+tMi0avY3z/7QTUxNf67B70u95UF/NLX98qHorKvRkaHuoavwB+yUsMzyoogOQwWZrwp12JbEKkmK4HAaTN2CpiXk37N3P3r4PsQMQUWpplqBPZVcZZNmqnpECOCH+ihU2WQsi6xruK/l04iCuUf0FDmJYtpGC91AlzTN7G1P+Z3eass0Ry4o6pZaN/CHgCVF200Y1GJnvFmiWqj/SJ5pgqOnzqW4ep90V26eObDcehlMdrK2cOhBL5Hz79clnggTLHM=
  app:
    master: software2projectprod
  on:
    repo: devpablin/Software2Project
  run:
  - rails db:migrate
